name: roslow

services:
    backend:
        build: .
        volumes:
            - uploads:/app/uploads
            - .:/app/
            - /app/node_modules
        ports:
            - "3001:3001"
        restart: unless-stopped
        networks:
            - roslow
        depends_on:
            - db
        environment:
            DATABASE_URL: "mongodb://monty:pass@db:27017/mydatabase?authSource=admin&directConnection=true"

    db:
        image: prismagraphql/mongo-single-replica:4.4.3-bionic
        platform: linux/amd64
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: monty
            MONGO_INITDB_ROOT_PASSWORD: pass
        networks:
            - roslow

    # frontend:
    #     build: ../client
    #     volumes:
    #         - ../client:/app:cached
    #         - /app/node_modules
    #     ports:
    #         - "5173:5173"
    #     restart: unless-stopped
    #     command: npm run dev -- --host
    #     networks:
    #         - roslow
    #     depends_on:
    #         - backend



volumes:
    uploads:

networks:
  roslow:
    driver: bridge